version: "3.7"

# This file allows you to maintain a copy of database
services:
  listener:
    build: .
    platform: linux/amd64
    image: fxdex/fx_ws
    logging:
      options:
        max-size: "512m"
    environment:
      # Toggles between different endpoint URLs
      - NETWORK=testnet                   # "local", "devnet", "testnet" or "mainnet"

      # Database connection credentials
      - database=fxdex
      - user=postgres
      - password=
      - host=
      - port=5432

      # RPC parameters
      - RPC_PAGE_SIZE=5                   # number of blocks to get in each multithread call
      - RPC_MAX_RETRIES=999               # number of times to retry before backing off
      - START_BLOCK=1                     # block to start tracking from
      - POSITIONING_UPDATE_INTERVAL=100   # block interval to update (unrealized) P&Ls

      # Endpoint URLs to DEX
      - TESTNET_RPC_URL=
      - TESTNET_GRPC_URL=
      - TESTNET_WS_URL=

      # For notifying user (in event of database/WS error)
      - GMAIL_APP_EMAIL=
      - GMAIL_APP_PASSWORD=
    networks:
      - default_network

  db:
    image: postgres:latest
    restart: always
    container_name: db
    shm_size: 512m  # https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: "512m"
    environment:
      # Database credentials should be same as above
      - POSTGRES_DB=fxdex
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_PORT=5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default_network

volumes:
  postgres-data:

networks:
  default_network:
    name: default_network
    driver: bridge