# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fx/oracle/packet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fx/oracle/packet.proto',
  package='fx.oracle',
  syntax='proto3',
  serialized_options=b'Z4git.wokoworks.com/blockchain/fx-chain/x/oracle/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x66x/oracle/packet.proto\x12\tfx.oracle\"A\n\x10OraclePacketData\x12#\n\x06noData\x18\x01 \x01(\x0b\x32\x11.fx.oracle.NoDataH\x00\x42\x08\n\x06packet\"\x08\n\x06NoDataB6Z4git.wokoworks.com/blockchain/fx-chain/x/oracle/typesb\x06proto3'
)




_ORACLEPACKETDATA = _descriptor.Descriptor(
  name='OraclePacketData',
  full_name='fx.oracle.OraclePacketData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='noData', full_name='fx.oracle.OraclePacketData.noData', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='packet', full_name='fx.oracle.OraclePacketData.packet',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=37,
  serialized_end=102,
)


_NODATA = _descriptor.Descriptor(
  name='NoData',
  full_name='fx.oracle.NoData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=112,
)

_ORACLEPACKETDATA.fields_by_name['noData'].message_type = _NODATA
_ORACLEPACKETDATA.oneofs_by_name['packet'].fields.append(
  _ORACLEPACKETDATA.fields_by_name['noData'])
_ORACLEPACKETDATA.fields_by_name['noData'].containing_oneof = _ORACLEPACKETDATA.oneofs_by_name['packet']
DESCRIPTOR.message_types_by_name['OraclePacketData'] = _ORACLEPACKETDATA
DESCRIPTOR.message_types_by_name['NoData'] = _NODATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OraclePacketData = _reflection.GeneratedProtocolMessageType('OraclePacketData', (_message.Message,), {
  'DESCRIPTOR' : _ORACLEPACKETDATA,
  '__module__' : 'fx.oracle.packet_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.OraclePacketData)
  })
_sym_db.RegisterMessage(OraclePacketData)

NoData = _reflection.GeneratedProtocolMessageType('NoData', (_message.Message,), {
  'DESCRIPTOR' : _NODATA,
  '__module__' : 'fx.oracle.packet_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.NoData)
  })
_sym_db.RegisterMessage(NoData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
