# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fx/oracle/post.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fx_py_sdk.codec.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fx/oracle/post.proto',
  package='fx.oracle',
  syntax='proto3',
  serialized_options=b'Z4git.wokoworks.com/blockchain/fx-chain/x/oracle/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x66x/oracle/post.proto\x12\tfx.oracle\x1a\x14gogoproto/gogo.proto\"\xba\x01\n\x0bOraclePrice\x12\n\n\x02id\x18\x01 \x01(\t\x12?\n\x04\x66rom\x18\x02 \x01(\x0c\x42\x31\xfa\xde\x1f-github.com/cosmos/cosmos-sdk/types.AccAddress\x12\x0f\n\x07pair_id\x18\x03 \x01(\t\x12=\n\x05price\x18\x04 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x12\x0e\n\x06\x65xpiry\x18\x05 \x01(\x03\"^\n\x0c\x43urrentPrice\x12\x0f\n\x07pair_id\x18\x01 \x01(\t\x12=\n\x05price\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\"E\n\rCurrentPrices\x12\x34\n\rcurrentPrices\x18\x01 \x03(\x0b\x32\x17.fx.oracle.CurrentPriceB\x04\xc8\xde\x1f\x00\"\x83\x01\n\x06Market\x12\x0f\n\x07pair_id\x18\x01 \x01(\t\x12\x12\n\nbase_asset\x18\x02 \x01(\t\x12\x13\n\x0bquote_asset\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x05 \x01(\x08\x12\x15\n\rprice_decimal\x18\x06 \x01(\x03\x12\x18\n\x10position_decimal\x18\x07 \x01(\x03\"]\n\x0bPostedPrice\x12\x0f\n\x07pair_id\x18\x01 \x01(\t\x12=\n\x05price\x18\x03 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\"B\n\x0cPostedPrices\x12\x32\n\x0cpostedPrices\x18\x01 \x03(\x0b\x32\x16.fx.oracle.PostedPriceB\x04\xc8\xde\x1f\x00\x42\x36Z4git.wokoworks.com/blockchain/fx-chain/x/oracle/typesb\x06proto3'
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_ORACLEPRICE = _descriptor.Descriptor(
  name='OraclePrice',
  full_name='fx.oracle.OraclePrice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='fx.oracle.OraclePrice.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from', full_name='fx.oracle.OraclePrice.from', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372\336\037-github.com/cosmos/cosmos-sdk/types.AccAddress', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pair_id', full_name='fx.oracle.OraclePrice.pair_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='fx.oracle.OraclePrice.price', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expiry', full_name='fx.oracle.OraclePrice.expiry', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=244,
)


_CURRENTPRICE = _descriptor.Descriptor(
  name='CurrentPrice',
  full_name='fx.oracle.CurrentPrice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pair_id', full_name='fx.oracle.CurrentPrice.pair_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='fx.oracle.CurrentPrice.price', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=340,
)


_CURRENTPRICES = _descriptor.Descriptor(
  name='CurrentPrices',
  full_name='fx.oracle.CurrentPrices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentPrices', full_name='fx.oracle.CurrentPrices.currentPrices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=411,
)


_MARKET = _descriptor.Descriptor(
  name='Market',
  full_name='fx.oracle.Market',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pair_id', full_name='fx.oracle.Market.pair_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_asset', full_name='fx.oracle.Market.base_asset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quote_asset', full_name='fx.oracle.Market.quote_asset', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active', full_name='fx.oracle.Market.active', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price_decimal', full_name='fx.oracle.Market.price_decimal', index=4,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_decimal', full_name='fx.oracle.Market.position_decimal', index=5,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=545,
)


_POSTEDPRICE = _descriptor.Descriptor(
  name='PostedPrice',
  full_name='fx.oracle.PostedPrice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pair_id', full_name='fx.oracle.PostedPrice.pair_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='fx.oracle.PostedPrice.price', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=640,
)


_POSTEDPRICES = _descriptor.Descriptor(
  name='PostedPrices',
  full_name='fx.oracle.PostedPrices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='postedPrices', full_name='fx.oracle.PostedPrices.postedPrices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=642,
  serialized_end=708,
)

_CURRENTPRICES.fields_by_name['currentPrices'].message_type = _CURRENTPRICE
_POSTEDPRICES.fields_by_name['postedPrices'].message_type = _POSTEDPRICE
DESCRIPTOR.message_types_by_name['OraclePrice'] = _ORACLEPRICE
DESCRIPTOR.message_types_by_name['CurrentPrice'] = _CURRENTPRICE
DESCRIPTOR.message_types_by_name['CurrentPrices'] = _CURRENTPRICES
DESCRIPTOR.message_types_by_name['Market'] = _MARKET
DESCRIPTOR.message_types_by_name['PostedPrice'] = _POSTEDPRICE
DESCRIPTOR.message_types_by_name['PostedPrices'] = _POSTEDPRICES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OraclePrice = _reflection.GeneratedProtocolMessageType('OraclePrice', (_message.Message,), {
  'DESCRIPTOR' : _ORACLEPRICE,
  '__module__' : 'fx.oracle.post_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.OraclePrice)
  })
_sym_db.RegisterMessage(OraclePrice)

CurrentPrice = _reflection.GeneratedProtocolMessageType('CurrentPrice', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTPRICE,
  '__module__' : 'fx.oracle.post_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.CurrentPrice)
  })
_sym_db.RegisterMessage(CurrentPrice)

CurrentPrices = _reflection.GeneratedProtocolMessageType('CurrentPrices', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTPRICES,
  '__module__' : 'fx.oracle.post_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.CurrentPrices)
  })
_sym_db.RegisterMessage(CurrentPrices)

Market = _reflection.GeneratedProtocolMessageType('Market', (_message.Message,), {
  'DESCRIPTOR' : _MARKET,
  '__module__' : 'fx.oracle.post_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.Market)
  })
_sym_db.RegisterMessage(Market)

PostedPrice = _reflection.GeneratedProtocolMessageType('PostedPrice', (_message.Message,), {
  'DESCRIPTOR' : _POSTEDPRICE,
  '__module__' : 'fx.oracle.post_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.PostedPrice)
  })
_sym_db.RegisterMessage(PostedPrice)

PostedPrices = _reflection.GeneratedProtocolMessageType('PostedPrices', (_message.Message,), {
  'DESCRIPTOR' : _POSTEDPRICES,
  '__module__' : 'fx.oracle.post_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.PostedPrices)
  })
_sym_db.RegisterMessage(PostedPrices)


DESCRIPTOR._options = None
_ORACLEPRICE.fields_by_name['from']._options = None
_ORACLEPRICE.fields_by_name['price']._options = None
_CURRENTPRICE.fields_by_name['price']._options = None
_CURRENTPRICES.fields_by_name['currentPrices']._options = None
_POSTEDPRICE.fields_by_name['price']._options = None
_POSTEDPRICES.fields_by_name['postedPrices']._options = None
# @@protoc_insertion_point(module_scope)
