# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fx/oracle/v1/genesis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fx_py_sdk.codec.fx.oracle.v1 import post_pb2 as fx_dot_oracle_dot_v1_dot_post__pb2
from fx_py_sdk.codec.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fx/oracle/v1/genesis.proto',
  package='fx.oracle.v1',
  syntax='proto3',
  serialized_options=b'Z*github.com/functionx/fx-dex/x/oracle/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x66x/oracle/v1/genesis.proto\x12\x0c\x66x.oracle.v1\x1a\x17\x66x/oracle/v1/post.proto\x1a\x14gogoproto/gogo.proto\"\xa6\x02\n\x0cGenesisState\x12+\n\x07markets\x18\x01 \x03(\x0b\x32\x14.fx.oracle.v1.MarketB\x04\xc8\xde\x1f\x00\x12\x36\n\x0cpostedPrices\x18\x02 \x01(\x0b\x32\x1a.fx.oracle.v1.PostedPricesB\x04\xc8\xde\x1f\x00\x12\x32\n\nbandOracle\x18\x03 \x01(\x0b\x32\x18.fx.oracle.v1.BandOracleB\x04\xc8\xde\x1f\x00\x12\x31\n\taggrators\x18\x04 \x03(\x0b\x32\x18.fx.oracle.v1.AggregatorB\x04\xc8\xde\x1f\x00\x12\x31\n\x06prices\x18\x05 \x01(\x0b\x32\x1b.fx.oracle.v1.CurrentPricesB\x04\xc8\xde\x1f\x00\x12\x17\n\x0foracleRequestId\x18\x06 \x01(\x04\"\x08\n\x06Params\"\xa9\x01\n\nBandOracle\x12\x13\n\x0brequest_key\x18\x01 \x01(\t\x12\x18\n\x10oracle_script_id\x18\x02 \x01(\x03\x12\x12\n\nmultiplier\x18\x03 \x01(\x04\x12\x13\n\x0bibc_version\x18\x04 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x05 \x01(\t\x12\x0c\n\x04port\x18\x06 \x01(\t\x12\x11\n\task_count\x18\x07 \x01(\x04\x12\x11\n\tmin_count\x18\x08 \x01(\x04\"X\n\x06\x41nswer\x12\x0e\n\x06oracle\x18\x01 \x01(\t\x12>\n\x06\x61nswer\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\"\xad\x01\n\nAggregator\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x30\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x1a.fx.oracle.v1.OracleConfigB\x04\xc8\xde\x1f\x00\x12\x18\n\x10round_start_time\x18\x03 \x01(\x03\x12/\n\x0bsubmissions\x18\x04 \x03(\x0b\x32\x14.fx.oracle.v1.AnswerB\x04\xc8\xde\x1f\x00\x12\x12\n\x04type\x18\x05 \x01(\tB\x04\xc8\xde\x1f\x01\"Z\n\x0cOracleConfig\x12\x0f\n\x07oracles\x18\x01 \x03(\t\x12\x1c\n\x14min_answer_threshold\x18\x02 \x01(\r\x12\x1b\n\x13staleness_threshold\x18\x03 \x01(\x03\x42,Z*github.com/functionx/fx-dex/x/oracle/typesb\x06proto3'
  ,
  dependencies=[fx_dot_oracle_dot_v1_dot_post__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_GENESISSTATE = _descriptor.Descriptor(
  name='GenesisState',
  full_name='fx.oracle.v1.GenesisState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='markets', full_name='fx.oracle.v1.GenesisState.markets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='postedPrices', full_name='fx.oracle.v1.GenesisState.postedPrices', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bandOracle', full_name='fx.oracle.v1.GenesisState.bandOracle', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aggrators', full_name='fx.oracle.v1.GenesisState.aggrators', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prices', full_name='fx.oracle.v1.GenesisState.prices', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='oracleRequestId', full_name='fx.oracle.v1.GenesisState.oracleRequestId', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=386,
)


_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='fx.oracle.v1.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=396,
)


_BANDORACLE = _descriptor.Descriptor(
  name='BandOracle',
  full_name='fx.oracle.v1.BandOracle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_key', full_name='fx.oracle.v1.BandOracle.request_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='oracle_script_id', full_name='fx.oracle.v1.BandOracle.oracle_script_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='multiplier', full_name='fx.oracle.v1.BandOracle.multiplier', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ibc_version', full_name='fx.oracle.v1.BandOracle.ibc_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel', full_name='fx.oracle.v1.BandOracle.channel', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='fx.oracle.v1.BandOracle.port', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ask_count', full_name='fx.oracle.v1.BandOracle.ask_count', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_count', full_name='fx.oracle.v1.BandOracle.min_count', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=568,
)


_ANSWER = _descriptor.Descriptor(
  name='Answer',
  full_name='fx.oracle.v1.Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='oracle', full_name='fx.oracle.v1.Answer.oracle', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='answer', full_name='fx.oracle.v1.Answer.answer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=658,
)


_AGGREGATOR = _descriptor.Descriptor(
  name='Aggregator',
  full_name='fx.oracle.v1.Aggregator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='fx.oracle.v1.Aggregator.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='fx.oracle.v1.Aggregator.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round_start_time', full_name='fx.oracle.v1.Aggregator.round_start_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='submissions', full_name='fx.oracle.v1.Aggregator.submissions', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='fx.oracle.v1.Aggregator.type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=661,
  serialized_end=834,
)


_ORACLECONFIG = _descriptor.Descriptor(
  name='OracleConfig',
  full_name='fx.oracle.v1.OracleConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='oracles', full_name='fx.oracle.v1.OracleConfig.oracles', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_answer_threshold', full_name='fx.oracle.v1.OracleConfig.min_answer_threshold', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='staleness_threshold', full_name='fx.oracle.v1.OracleConfig.staleness_threshold', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=836,
  serialized_end=926,
)

_GENESISSTATE.fields_by_name['markets'].message_type = fx_dot_oracle_dot_v1_dot_post__pb2._MARKET
_GENESISSTATE.fields_by_name['postedPrices'].message_type = fx_dot_oracle_dot_v1_dot_post__pb2._POSTEDPRICES
_GENESISSTATE.fields_by_name['bandOracle'].message_type = _BANDORACLE
_GENESISSTATE.fields_by_name['aggrators'].message_type = _AGGREGATOR
_GENESISSTATE.fields_by_name['prices'].message_type = fx_dot_oracle_dot_v1_dot_post__pb2._CURRENTPRICES
_AGGREGATOR.fields_by_name['config'].message_type = _ORACLECONFIG
_AGGREGATOR.fields_by_name['submissions'].message_type = _ANSWER
DESCRIPTOR.message_types_by_name['GenesisState'] = _GENESISSTATE
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
DESCRIPTOR.message_types_by_name['BandOracle'] = _BANDORACLE
DESCRIPTOR.message_types_by_name['Answer'] = _ANSWER
DESCRIPTOR.message_types_by_name['Aggregator'] = _AGGREGATOR
DESCRIPTOR.message_types_by_name['OracleConfig'] = _ORACLECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenesisState = _reflection.GeneratedProtocolMessageType('GenesisState', (_message.Message,), {
  'DESCRIPTOR' : _GENESISSTATE,
  '__module__' : 'fx.oracle.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.v1.GenesisState)
  })
_sym_db.RegisterMessage(GenesisState)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'fx.oracle.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.v1.Params)
  })
_sym_db.RegisterMessage(Params)

BandOracle = _reflection.GeneratedProtocolMessageType('BandOracle', (_message.Message,), {
  'DESCRIPTOR' : _BANDORACLE,
  '__module__' : 'fx.oracle.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.v1.BandOracle)
  })
_sym_db.RegisterMessage(BandOracle)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), {
  'DESCRIPTOR' : _ANSWER,
  '__module__' : 'fx.oracle.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.v1.Answer)
  })
_sym_db.RegisterMessage(Answer)

Aggregator = _reflection.GeneratedProtocolMessageType('Aggregator', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATOR,
  '__module__' : 'fx.oracle.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.v1.Aggregator)
  })
_sym_db.RegisterMessage(Aggregator)

OracleConfig = _reflection.GeneratedProtocolMessageType('OracleConfig', (_message.Message,), {
  'DESCRIPTOR' : _ORACLECONFIG,
  '__module__' : 'fx.oracle.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:fx.oracle.v1.OracleConfig)
  })
_sym_db.RegisterMessage(OracleConfig)


DESCRIPTOR._options = None
_GENESISSTATE.fields_by_name['markets']._options = None
_GENESISSTATE.fields_by_name['postedPrices']._options = None
_GENESISSTATE.fields_by_name['bandOracle']._options = None
_GENESISSTATE.fields_by_name['aggrators']._options = None
_GENESISSTATE.fields_by_name['prices']._options = None
_ANSWER.fields_by_name['answer']._options = None
_AGGREGATOR.fields_by_name['config']._options = None
_AGGREGATOR.fields_by_name['submissions']._options = None
_AGGREGATOR.fields_by_name['type']._options = None
# @@protoc_insertion_point(module_scope)
