# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fx/dex/v1/genesis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fx_py_sdk.codec.fx.dex.v1 import funding_pb2 as fx_dot_dex_dot_v1_dot_funding__pb2
from fx_py_sdk.codec.fx.dex.v1 import margin_pb2 as fx_dot_dex_dot_v1_dot_margin__pb2
from fx_py_sdk.codec.fx.dex.v1 import match_pb2 as fx_dot_dex_dot_v1_dot_match__pb2
from fx_py_sdk.codec.fx.dex.v1 import order_pb2 as fx_dot_dex_dot_v1_dot_order__pb2
from fx_py_sdk.codec.fx.dex.v1 import params_pb2 as fx_dot_dex_dot_v1_dot_params__pb2
from fx_py_sdk.codec.fx.dex.v1 import position_pb2 as fx_dot_dex_dot_v1_dot_position__pb2
from fx_py_sdk.codec.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fx/dex/v1/genesis.proto',
  package='fx.dex.v1',
  syntax='proto3',
  serialized_options=b'Z\'github.com/functionx/fx-dex/x/dex/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x66x/dex/v1/genesis.proto\x12\tfx.dex.v1\x1a\x17\x66x/dex/v1/funding.proto\x1a\x16\x66x/dex/v1/margin.proto\x1a\x15\x66x/dex/v1/match.proto\x1a\x15\x66x/dex/v1/order.proto\x1a\x16\x66x/dex/v1/params.proto\x1a\x18\x66x/dex/v1/position.proto\x1a\x14gogoproto/gogo.proto\"\x8c\x07\n\x0cGenesisState\x12<\n\x12pair_funding_rates\x18\x01 \x03(\x0b\x32\x1a.fx.dex.v1.PairFundingRateB\x04\xc8\xde\x1f\x00\x12.\n\x0c\x66unding_info\x18\x02 \x01(\x0b\x32\x12.fx.dex.v1.FundingB\x04\xc8\xde\x1f\x00\x12\x32\n\x0c\x66unding_time\x18\x03 \x01(\x0b\x32\x16.fx.dex.v1.FundingTimeB\x04\xc8\xde\x1f\x00\x12?\n\x14premium_index_config\x18\x04 \x01(\x0b\x32\x1b.fx.dex.v1.PremiumIndexConfB\x04\xc8\xde\x1f\x00\x12\x34\n\rpremium_index\x18\x05 \x03(\x0b\x32\x17.fx.dex.v1.PremiumIndexB\x04\xc8\xde\x1f\x00\x12\x37\n\x12margin_rate_tables\x18\x08 \x03(\x0b\x32\x15.fx.dex.v1.MarginRateB\x04\xc8\xde\x1f\x00\x12@\n\x17init_margin_rate_tables\x18\t \x03(\x0b\x32\x19.fx.dex.v1.InitMarginRateB\x04\xc8\xde\x1f\x00\x12.\n\ndeal_price\x18\n \x03(\x0b\x32\x14.fx.dex.v1.DealPriceB\x04\xc8\xde\x1f\x00\x12&\n\x06orders\x18\x0b \x03(\x0b\x32\x10.fx.dex.v1.OrderB\x04\xc8\xde\x1f\x00\x12\'\n\x06params\x18\x0c \x01(\x0b\x32\x11.fx.dex.v1.ParamsB\x04\xc8\xde\x1f\x00\x12,\n\tpositions\x18\r \x03(\x0b\x32\x13.fx.dex.v1.PositionB\x04\xc8\xde\x1f\x00\x12\x30\n\x0bposition_id\x18\x0e \x01(\x0b\x32\x15.fx.dex.v1.PositionIDB\x04\xc8\xde\x1f\x00\x12\x37\n\tma_params\x18\x0f \x01(\x0b\x32\x1e.fx.dex.v1.MovingAverageParamsB\x04\xc8\xde\x1f\x00\x12.\n\ndepth_book\x18\x10 \x03(\x0b\x32\x14.fx.dex.v1.DepthBookB\x04\xc8\xde\x1f\x00\x12\x1d\n\x0f\x64\x65pth_book_keys\x18\x11 \x03(\tB\x04\xc8\xde\x1f\x00\x12!\n\x13order_book_ids_keys\x18\x12 \x03(\tB\x04\xc8\xde\x1f\x00\x12\x31\n\x0eorder_book_ids\x18\x13 \x03(\x0b\x32\x13.fx.dex.v1.OrderIDsB\x04\xc8\xde\x1f\x00\x12)\n\x07reserve\x18\x14 \x01(\x0b\x32\x12.fx.dex.v1.ReserveB\x04\xc8\xde\x1f\x00\x42)Z\'github.com/functionx/fx-dex/x/dex/typesb\x06proto3'
  ,
  dependencies=[fx_dot_dex_dot_v1_dot_funding__pb2.DESCRIPTOR,fx_dot_dex_dot_v1_dot_margin__pb2.DESCRIPTOR,fx_dot_dex_dot_v1_dot_match__pb2.DESCRIPTOR,fx_dot_dex_dot_v1_dot_order__pb2.DESCRIPTOR,fx_dot_dex_dot_v1_dot_params__pb2.DESCRIPTOR,fx_dot_dex_dot_v1_dot_position__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_GENESISSTATE = _descriptor.Descriptor(
  name='GenesisState',
  full_name='fx.dex.v1.GenesisState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pair_funding_rates', full_name='fx.dex.v1.GenesisState.pair_funding_rates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='funding_info', full_name='fx.dex.v1.GenesisState.funding_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='funding_time', full_name='fx.dex.v1.GenesisState.funding_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='premium_index_config', full_name='fx.dex.v1.GenesisState.premium_index_config', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='premium_index', full_name='fx.dex.v1.GenesisState.premium_index', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='margin_rate_tables', full_name='fx.dex.v1.GenesisState.margin_rate_tables', index=5,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='init_margin_rate_tables', full_name='fx.dex.v1.GenesisState.init_margin_rate_tables', index=6,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deal_price', full_name='fx.dex.v1.GenesisState.deal_price', index=7,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orders', full_name='fx.dex.v1.GenesisState.orders', index=8,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='fx.dex.v1.GenesisState.params', index=9,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='positions', full_name='fx.dex.v1.GenesisState.positions', index=10,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_id', full_name='fx.dex.v1.GenesisState.position_id', index=11,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ma_params', full_name='fx.dex.v1.GenesisState.ma_params', index=12,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth_book', full_name='fx.dex.v1.GenesisState.depth_book', index=13,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth_book_keys', full_name='fx.dex.v1.GenesisState.depth_book_keys', index=14,
      number=17, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order_book_ids_keys', full_name='fx.dex.v1.GenesisState.order_book_ids_keys', index=15,
      number=18, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order_book_ids', full_name='fx.dex.v1.GenesisState.order_book_ids', index=16,
      number=19, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reserve', full_name='fx.dex.v1.GenesisState.reserve', index=17,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=1114,
)

_GENESISSTATE.fields_by_name['pair_funding_rates'].message_type = fx_dot_dex_dot_v1_dot_funding__pb2._PAIRFUNDINGRATE
_GENESISSTATE.fields_by_name['funding_info'].message_type = fx_dot_dex_dot_v1_dot_funding__pb2._FUNDING
_GENESISSTATE.fields_by_name['funding_time'].message_type = fx_dot_dex_dot_v1_dot_funding__pb2._FUNDINGTIME
_GENESISSTATE.fields_by_name['premium_index_config'].message_type = fx_dot_dex_dot_v1_dot_funding__pb2._PREMIUMINDEXCONF
_GENESISSTATE.fields_by_name['premium_index'].message_type = fx_dot_dex_dot_v1_dot_funding__pb2._PREMIUMINDEX
_GENESISSTATE.fields_by_name['margin_rate_tables'].message_type = fx_dot_dex_dot_v1_dot_margin__pb2._MARGINRATE
_GENESISSTATE.fields_by_name['init_margin_rate_tables'].message_type = fx_dot_dex_dot_v1_dot_margin__pb2._INITMARGINRATE
_GENESISSTATE.fields_by_name['deal_price'].message_type = fx_dot_dex_dot_v1_dot_match__pb2._DEALPRICE
_GENESISSTATE.fields_by_name['orders'].message_type = fx_dot_dex_dot_v1_dot_order__pb2._ORDER
_GENESISSTATE.fields_by_name['params'].message_type = fx_dot_dex_dot_v1_dot_params__pb2._PARAMS
_GENESISSTATE.fields_by_name['positions'].message_type = fx_dot_dex_dot_v1_dot_position__pb2._POSITION
_GENESISSTATE.fields_by_name['position_id'].message_type = fx_dot_dex_dot_v1_dot_position__pb2._POSITIONID
_GENESISSTATE.fields_by_name['ma_params'].message_type = fx_dot_dex_dot_v1_dot_funding__pb2._MOVINGAVERAGEPARAMS
_GENESISSTATE.fields_by_name['depth_book'].message_type = fx_dot_dex_dot_v1_dot_match__pb2._DEPTHBOOK
_GENESISSTATE.fields_by_name['order_book_ids'].message_type = fx_dot_dex_dot_v1_dot_order__pb2._ORDERIDS
_GENESISSTATE.fields_by_name['reserve'].message_type = fx_dot_dex_dot_v1_dot_params__pb2._RESERVE
DESCRIPTOR.message_types_by_name['GenesisState'] = _GENESISSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenesisState = _reflection.GeneratedProtocolMessageType('GenesisState', (_message.Message,), {
  'DESCRIPTOR' : _GENESISSTATE,
  '__module__' : 'fx.dex.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:fx.dex.v1.GenesisState)
  })
_sym_db.RegisterMessage(GenesisState)


DESCRIPTOR._options = None
_GENESISSTATE.fields_by_name['pair_funding_rates']._options = None
_GENESISSTATE.fields_by_name['funding_info']._options = None
_GENESISSTATE.fields_by_name['funding_time']._options = None
_GENESISSTATE.fields_by_name['premium_index_config']._options = None
_GENESISSTATE.fields_by_name['premium_index']._options = None
_GENESISSTATE.fields_by_name['margin_rate_tables']._options = None
_GENESISSTATE.fields_by_name['init_margin_rate_tables']._options = None
_GENESISSTATE.fields_by_name['deal_price']._options = None
_GENESISSTATE.fields_by_name['orders']._options = None
_GENESISSTATE.fields_by_name['params']._options = None
_GENESISSTATE.fields_by_name['positions']._options = None
_GENESISSTATE.fields_by_name['position_id']._options = None
_GENESISSTATE.fields_by_name['ma_params']._options = None
_GENESISSTATE.fields_by_name['depth_book']._options = None
_GENESISSTATE.fields_by_name['depth_book_keys']._options = None
_GENESISSTATE.fields_by_name['order_book_ids_keys']._options = None
_GENESISSTATE.fields_by_name['order_book_ids']._options = None
_GENESISSTATE.fields_by_name['reserve']._options = None
# @@protoc_insertion_point(module_scope)
